=== sysvyz/anaN/resources/tree-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.sysvyz.org"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="node" type="sys:nodeType" xmlns:sys="http://www.sysvyz.org"/>

    <xs:complexType name="exponentType">
        <xs:sequence>
            <xs:element type="sys:nodeType" name="node" xmlns:sys="http://www.sysvyz.org"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constantType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="variableType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="value" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="baseType">
        <xs:sequence>
            <xs:element type="sys:nodeType" name="node" xmlns:sys="http://www.sysvyz.org"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="powerType">
        <xs:sequence>
            <xs:element type="sys:baseType" name="base" minOccurs="1" maxOccurs="1" xmlns:sys="http://www.sysvyz.org"/>
            <xs:element type="sys:exponentType" name="exponent" minOccurs="1" maxOccurs="1"  xmlns:sys="http://www.sysvyz.org"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nodeType">
        <xs:choice>
            <xs:element type="sys:variableType" name="variable" minOccurs="0" xmlns:sys="http://www.sysvyz.org"/>
            <xs:element type="sys:constantType" name="constant" minOccurs="0" xmlns:sys="http://www.sysvyz.org"/>
            <xs:element type="sys:multiplicationType" name="multiplication" minOccurs="0"
                        xmlns:sys="http://www.sysvyz.org"/>
            <xs:element type="sys:powerType" name="power" minOccurs="0" xmlns:sys="http://www.sysvyz.org"/>
            <xs:element type="sys:additionType" name="addition" minOccurs="0" xmlns:sys="http://www.sysvyz.org"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="additionType">
        <xs:sequence>
            <xs:element type="sys:nodeType" name="node" maxOccurs="unbounded" minOccurs="0"
                        xmlns:sys="http://www.sysvyz.org"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="multiplicationType">
        <xs:sequence>
            <xs:element type="sys:nodeType" name="node" maxOccurs="unbounded" minOccurs="0"
                        xmlns:sys="http://www.sysvyz.org"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="type" use="optional"/>
    </xs:complexType>

</xs:schema>

=== sysvyz/anaN/test.xml
<?xml version="1.0"?>
<node xmlns="http://www.sysvyz.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sysvyz.org resources/tree-schema.xsd">
    <multiplication type="array">
        <node>
            <addition>
                <node>
                    <variable value="x"/>
                </node>
                <node>
                    <constant value="67"/>
                </node>
            </addition>
        </node>
        <node>
            <power>
                <base>
                    <node>
                        <multiplication type="array">
                            <node>
                                <variable value="x"/>
                            </node>
                            <node>
                                <constant value="4"/>
                            </node>
                            <node>
                                <variable value="x"/>
                            </node>
                            <node>
                                <addition>
                                    <node>
                                        <multiplication type="array">
                                            <node>
                                                <variable value="x"/>
                                            </node>
                                            <node>
                                                <constant value="67"/>
                                            </node>
                                        </multiplication>
                                    </node>
                                    <node>
                                        <power>
                                            <base>
                                                <node>
                                                    <multiplication type="array">
                                                        <node>
                                                            <variable value="x"/>
                                                        </node>
                                                        <node>
                                                            <constant value="24"/>
                                                        </node>
                                                    </multiplication>
                                                </node>
                                            </base>
                                            <exponent>
                                                <node>
                                                    <constant value="2"/>
                                                </node>
                                            </exponent>
                                        </power>
                                    </node>
                                </addition>
                            </node>
                        </multiplication>
                    </node>
                </base>
                <exponent>
                    <node>
                        <constant value="2"/>
                    </node>
                </exponent>
            </power>
        </node>
    </multiplication>
</node>
